services:
  nextjs-app:
    build:
      context: .

    container_name: nextjs-app

    volumes:
      - ./public/config.js:/app/public/config.js

    ports:
      - "8000:3000"

    restart: always
